name: Build & Deploy [Prod]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install"
        run: yarn # install all the dependencies for the whole project

      - name: "Build"
        run: yarn build # this builds all the packages and apps at the same time

      # DEPLOY FE
      - name: "Install Vercel CLI"
        run: npm install --global vercel@canary
      - name: "Pull Vercel Environment Information"
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: "Build Project Artifacts"
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: "Deploy Project Artifacts to Vercel"
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: "Assign custom domain"
        run: |
          url="$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" dollardaddy.app
